config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Devise Routes for Admin
  
  devise_for :admins, path: 'admins', controllers: 
  {sessions: "admins/sessions",
   registrations: "admins/registrations",
   masquerades: "admins/masquerades"}
  
  # Devise Routes for Users
  devise_for :users, path: 'users', controllers: 
  {sessions: "users/sessions",
   registrations: "users/registrations",
   masquerades: "admins/masquerades"}

  resources :charts, only:[] do 
    collection do 
      get 'all_royalties_by_month'
      get 'revenue_by_state'
      get 'collections_by_category'
      get 'collections_by_month'
    end
  end
  
  # Custom Routes for Errors
  get '/404', :to => "errors#not_found"
  get '/422', :to => "errors#unacceptable"
  get '/500', :to => "errors#server_error"
  get '/cookies', :to => "cookies#index"
  
  # Routes for Signing Up
  get '/signup' => 'signups#index'
  post '/signup' => 'signups#create'

  # Authenticated route to show specific Dashboard for users
  authenticated :user do 
  	root to: 'public#userpage', as: "authenticated_user" 
    post '/' => 'public#userpage'
  end
  
  # Authenticate users before accessing these routes
  authenticate :user do  
    resources :users
    resources :franchises, only: [:edit, :update]
    resources :accountants, only: [:show]
    resources :insurances, only: [:show]
    resources :bank_accounts
    resources :credit_cards
    resources :website_preferences, except: :destroy
    resources :financials
    resources :remittances
    post '/remittances/new' => 'remittances#new'
    resources :franchise_documents, except: [:show, :edit, :update]
    resources :invoices
    resources :deposit_trackings


    get '/bank_routings/bank_name' => 'bank_routings#bank_name'
  end
  
  # Authenticated route to show specific Dashboard for admins
  authenticated :admin do 
  	root to: 'public#adminpage', as: "authenticated_admin" 
    post '/' => 'public#adminpage'
  end
  
  # Authenticate admins before accessing these routes
  authenticate :admin do 
    mount Logster::Web, at: "/logs"
    mount Sidekiq::Web => '/sidekiq'
    # Namespace the Admin pages
    namespace :admins do 
      resources :users
      resources :admins
      resources :franchises
      resources :franchises_select
      resources :credits
      resources :franchise_documents
      get 'credits/audit/:id', to: "credits#audit", as: 'credit_audit'
      resources :charges
      get 'charges/audit/:id', to: "charges#audit", as: 'charge_audit'
      get 'franchises/audit/:id' ,to: "franchises#audit", as: 'franchise_audit'
      resources :accountants
      get 'accountants/audit/:id' ,to: "accountants#audit", as: 'accountant_audit'
      resources :insurances
      get 'insurances/audit/:id' ,to: "insurances#audit", as: 'insurance_audit'
      resources :website_preferences
      get 'website_preferences/audit/:id', to: "website_preferences#audit", as: 'website_preference_audit'
      resources :financials
      get 'financials/audit/:id', to: "financials#audit", as: 'financials_audit'
      resources :remittances
      get 'remittances/audit/:id', to: "remittances#audit", as: 'remittances_audit'
      resources :invoices
      get 'invoices/audit/:id', to: "invoices#audit", as: 'invoices_audit'
      resources :transaction_codes
      get '/switch_user', to: "switch_user#index"

      #Reports
      scope module: :reports do 
        #Franchise List
        get '/franchise_list' => 'franchise_list#index'
        post '/franchise_list/render' => 'franchise_list#report'
        get '/franchise_list/render' => redirect('/admins/franchise_list')

        get '/franchise_expiration' => 'franchise_expiration#index'
        post '/franchise_expiration/render' => 'franchise_expiration#report'
        get '/franchise_expiration/render' => redirect('/admins/franchise_expiration')

        get '/franchise_advanced_rebate' => 'franchise_advanced_rebate#report'
        post '/franchise_advanced_rebate' => 'franchise_advanced_rebate#report'

        get '/franchise_prior_rebate' => 'franchise_prior_rebate#report'
        post '/franchise_prior_rebate' => 'franchise_prior_rebate#report'

        get '/insurance_expiration' => 'insurance_expiration#index'
        post '/insurance_expiration/render' => 'insurance_expiration#report'
        get '/insurance_expiration/render' => redirect('/admins/insurance_expiration')

        get '/insurance_missing' => 'insurance_missing#index'
        post '/insurance_missing/render' => 'insurance_missing#report'
        get '/insurance_missing/render' => redirect('/admins/insurance_missing')

        get '/payment_methods' => 'payment_methods#index'
        post '/payment_methods/render' => 'payment_methods#report'
        get '/payment_methods/render' => redirect('/admins/payment_methods')

        get 'payment_methods_missing' => 'payment_methods_missing#index'
        post '/payment_methods_missing/render' => 'payment_methods_missing#report'
        get '/payment_methods_missing/render' => redirect('/admins/payment_methods_missing')

        get '/website_preferences_list' => 'website_preferences_list#index'
        post '/website_preferences_list/render' => 'website_preferences_list#report'
        get '/website_preferences_list/render' => redirect('/admins/website_preferences_list')

        get '/website_preferences_missing' => 'website_preferences_missing#index'
        post '/website_preferences_missing/render' => 'website_preferences_missing#report'
        get '/website_preferences_missing/render' => redirect('/admins/website_preferences_missing')

        get '/financial_status' => 'financial_status#index'
        post '/financial_status/render' => 'financial_status#report'
        get '/financial_status/render' => redirect('/admins/financial_status')

        get '/financial_count_averages' => 'financial_count_and_averages#index'
        post '/financial_count_averages/render' => 'financial_count_and_averages#report'
        get '/financial_count_averages/render' => redirect('/admins/financial_count_averages')

        get '/financial_aggregation' => 'financial_aggregation#index'
        post '/financial_aggregation/render' => 'financial_aggregation#report'
        get '/financial_aggregation/render' => redirect('/admins/financial_aggregation')


      end

    end
  end
  
root to: 'public#main'
  
  
end

app/models/credit_card.rb
# frozen_string_literal: true

class CreditCard < ApplicationRecord
  # t.bigint franchise_id
  # t.string card_type
  # t.string last_four
  # t.integer exp_year
  # t.integer exp_month
  # t.string card_token
  # t.string slug
  CARD_TYPES = { 'V' => 'Visa',
                 'M' => 'MasterCard',
                 'I' => 'Discover',
                 'A' => 'American Express' }.freeze
  CARD_ICONS = { 'V' => 'fab fa-cc-visa light-grey-icon',
                 'M' => 'fab fa-cc-mastercard light-grey-icon',
                 'I' => 'fab fa-cc-discover light-grey-icon',
                 'A' => 'fab fa-cc-amex light-grey-icon' }.freeze

  extend FriendlyId

  friendly_id :franchise_name_card_lastfour, use: :slugged

  belongs_to :franchise

  audited

  attr_accessor :cc_number, :cc_type, :cc_exp_month, :cc_exp_year,
                :cc_address, :cc_city, :cc_state, :cc_zip, :cc_name

  validates :franchise, presence: true
  validates :cc_number, presence: true
  validates :cc_number, length: { minimum: 15, maximum: 16, message: :wrong_size }, allow_blank: false
  validates :cc_exp_month, presence: true
  validates :cc_exp_year, presence: true
  validates :cc_type, presence: true
  validates :cc_name, presence: true
  validates :cc_address, presence: true
  validates :cc_city, presence: true
  validates :cc_state, presence: true
  validates :cc_zip, presence: true

  before_destroy :verify_if_used

  def should_generate_new_friendly_id?
    new_record? || name_or_number_has_changed? || super
  end

  def franchise_name_card_lastfour
    [franchise&.number_and_name, card_type_desc, last_four].join('-')
  end

  def card_type_desc
    CARD_TYPES[card_type]
  end

  def card_icon
    CARD_ICONS[card_type]
  end

  def expiring_data
    "#{exp_month} / #{exp_year}"
  end

  def card_type_and_number
    "#{card_type_desc} #{I18n.t('credit_card.ending_in')} #{last_four}"
  end

  def name_or_number_has_changed?
    last_four_changed? || card_type_changed?
  end

  def expired?
    exp_year < Date.today.year % 100 || (exp_year == Date.today.year % 100 && exp_month < Date.today.month)
  end

  def expiring?
    next_month = (Date.today + 1.month).beginning_of_month
    in_two_months = (Date.today + 2.month).end_of_month
    range_to_check = (next_month..in_two_months)
    expiration_date = Date.new(2000 + exp_year, exp_month, 15)
    range_to_check.include?(expiration_date)
  end

  def used_in_auto_payments?
    WebsitePreference.exists?(payment_token: card_token)
  end

  def verify_if_used
    return unless used_in_auto_payments?

    errors.add(:base, 'This card is being used for a recurring payment.')
    throw(:abort)
  end

  def self.expiring_cards(franchise_id)
    cards = CreditCard.where('franchise_id = ?', franchise_id)
    cards.select { |card| card.expiring? }
  end

  def self.expired_cards(franchise_id)
    cards = CreditCard.where('franchise_id = ?', franchise_id)
    cards.select { |card| card.expired? }
  end

  def self.generate_dropdown_values(franchise_id)
    values = CreditCard.select(:card_token, :card_type, :last_four).where(franchise_id: franchise_id)
    values.each do |v|
      v.card_type = v.card_type_desc
    end
    values
  end
end

app/controllers/credit_cards_controller.rb
# frozen_string_literal: true

# For Users to List, Add, Edit, Delete Credit Cards
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: %i[edit destroy update]
  before_action :set_years, only: %i[edit update new create]

  def index
    @credit_cards = current_user.franchise.credit_cards.order(:id)
    authorize! :read, CreditCard
  end

  def new
    @credit_card = current_user.franchise.credit_cards.new
    authorize! :new, @credit_card
  end

  def create
    authorize! :create, CreditCard
    result = CreateCreditCard.call(params: credit_card_params, user: current_authenticated)
    if result.success?
      flash[:success] = I18n.t('credit_card.create.confirm')
      redirect_to credit_cards_path
    else
      @credit_card = result.credit_card
      render action: :new
    end
  end

  def edit
    authorize! :edit, @credit_card
    result = RetrieveCreditCard.call(account: @credit_card, user: current_authenticated)
    @credit_card = result.credit_card
  end

  def update
    authorize! :update, @credit_card
    @credit_card.assign_attributes(credit_card_params)
    result = UpdateCreditCard.call(account: @credit_card, params: credit_card_params, user: current_authenticated)
    if result.success?
      flash[:success] = I18n.t('credit_card.update.confirm')
      redirect_to credit_cards_path
    else
      @credit_card = result.credit_card
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @credit_card
    if @credit_card.destroy
      flash[:success] = I18n.t('credit_card.delete.confirm')
    else
      flash[:danger] = @credit_card.errors.full_messages.to_sentence
    end
    redirect_to credit_cards_path
  end

  private

  def set_credit_card
    @credit_card = CreditCard.friendly.find(params[:id])
  end

  def set_years
    d = Date.today
    @years = (d.strftime('%y')..d.next_year(10).strftime('%y')).to_a
  end

  def credit_card_params
    params.require(:credit_card)
          .permit(:franchise_id, :cc_type, :cc_number,
                  :cc_exp_month, :cc_exp_year, :cc_name, :cc_address,
                  :cc_city, :cc_state, :cc_zip)
  end
end

app/helpers/credit_card_helper.rb
module CreditCardHelper
  def card_status(card)
  	rtn_html = ""
    if card.expired?
  			rtn_html = <<-HTML
        <i class="fas fa-exclamation-circle fa-2x attention-icon" 
        style="margin: 0px 5px;" 
        aria-hidden="true" 
        data-html = "true" 
        data-toggle="tooltip" 
        title="#{I18n.t('credit_card.index.has_expired')}"
        data-placement = "right" data-container="body">
       </i>
       HTML
    else
      if card.expiring?
        rtn_html = <<-HTML
        <i class="fas fa-exclamation-circle fa-2x warning-icon" 
        style="margin: 0px 5px;" 
        aria-hidden="true" 
        data-html = "true" 
        data-toggle="tooltip" 
        title="#{I18n.t('credit_card.index.is_expiring')}"
        data-placement = "right" data-container="body">
       </i>
       HTML
      end
    end  

    rtn_html.html_safe    
  
  end

  def card_used(card)
    rtn_html = ""
    if card.used_in_auto_payments?
    rtn_html = <<-HTML
        <i class="far fa-calendar fa-2x attention-icon"
        style="margin: 0px 5px;" 
        aria-hidden="true" 
        data-html = "true" 
        data-toggle="tooltip" 
        title="#{I18n.t('credit_card.index.used_in_auto_payments')}"
        data-placement = "right" data-container="body">
       </i>
       HTML
     end

       rtn_html.html_safe
  end

  def destination_button(destination,franchise, pct_width)
    rtn_html = ""
    route = ""
      case destination 
      when 'add_royalty'
        route = new_remittance_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.enter_royalty')
      when 'add_receivable'
        route = new_receivable_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.add_charge')
      when 'add_invoice'
        route = new_invoice_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.add_invoice')
      when 'add_payment'
        route = new_check_payment_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.enter_check')
      when 'add_credit'
        route = new_franchise_credit_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.enter_credit')
      when 'add_accountant'
        route = new_admins_accountant_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.add_accountant')
      when 'support'
        route = supports_path(franchise_id: franchise.id)
      when 'add_insurance'
        route = new_admins_insurance_path(franchise_id: franchise.id)
        button_text = I18n.t('franchise_select.add_insurance')
      end

      rtn_html = <<-HTML     
        <td class = "text-nowrap" width="#{pct_width}%" style="text-align:right">
          <a data-turbolinks="false" href="#{route}" class="btn btn-sm btn-padgett">#{button_text}</a>
        </td>
      HTML
    
    rtn_html.html_safe
  end
end

app/views/credit_cards/_credit_card_list.html.erb
<div id = "table-scroll"
	 class = "table-scroll">
  <table id = "credit-card-list"
         class = "table-striped">
	<thead id = "list">
      <tr>
        <!-- Card Type -->
        <th scope = "col" class = "td-left">
        	<%=I18n.t('credit_card.index.card_type')%>
        </th>

        <!-- Ending In -->
        <th scope = "col" class = "td-left">
        	<%=I18n.t('credit_card.index.ending_in')%>
        </th>

        <!-- Expires -->
        <th scope = "col" class = "td-center">
            <%=I18n.t('credit_card.index.expiring')%>
        </th>        
            
        <th>Warnings</th>

        <th></th>

        <th></th>
      </tr>
    </thead>

    <% if @credit_cards.size > 0 %>
      <tbody>    
    	<%@credit_cards.each do |card|%>
    	  <tr>
            <!-- Card Type -->
    	    <td data-name = "Card Type"
    	      	scope = "col"
    	      	class = "td-left">
    	  	    <%=content_tag(:i, '', 
                class: card.card_icon+" fa-3x")%>
    	  	</td>

            <!-- Ending In -->
    	  	<td data-name = "Ending In" 
    	  	   	scope = "col"
    	  	   	class = "td-left">
     	  	    <%=card.last_four%>
    	  	</td>
            
            <!-- Expiration -->
            <td data-name = "Expires" 
                scope = "col"
                class = "td-center">
                <%=card.expiring_data%>
            </td>
            
            
            <td> 
              <!-- Card Status -->   
              <%=card_status(card)%>
              <!-- Card being Used for Recurring Payment? -->
              <%=card_used(card)%>
            </td>
    	  	
            <!-- Edit Link if User can Edit -->
    	  	<%if can? :edit, card %>
    	  	  <td data-name = ""
    	  	      class = "td-center">
    	  	      <%=link_with_icon(edit_credit_card_path(card),
    	  	      "edit",
    	  	      I18n.t('credit_card.index.edit_link'),
    	  	      "",
    	  	      false)%>
    	  	  </td>
    	  	<%else%>   
    	  	  <td></td>
    	  	<%end%>
            
            <!-- Delete Link if User can Delete -->
    	  	<%if can? :delete, card%>
    	  	  <td data-name = ""
    	  	   	  class = "td-center">
    	  	      <%=link_with_icon(credit_card_path(id: card),
    	  	      "delete",
    	  	      I18n.t('credit_card.index.delete_link'),
    	  	      I18n.t('credit_card.index.delete_confirm'),
    	  	      false)%>
    	  	  </td>
    	  	<%else%>
    	  	  <td></td>
    	  	<%end%>
    	  </tr>
   	  	<%end%>
      </tbody>
  	<%end%>
  </table>
</div>  	

app/views/credit_cards/_form.html.erb
<div class = "card">
  <div class = "card-header login-header">
    <h4>
      <%if action == "edit"%>
        <%=I18n.t('credit_card.form.edit_title',
        { card_type: credit_card.card_type_desc,
          last_four: credit_card.last_four})%>
      <%else%>
        <%=I18n.t('credit_card.form.create_title')%>
      <%end%>
    </h4>
  </div>
  
  <%= form_for credit_card do |f| %>
    <div class = "card-body card-background-padgett">
      <div class = "form-row col-12">
        <%=f.hidden_field :franchise_id, value: f.object.franchise_id%>
        <!-- CARD TYPE -->   
        <div class = "form-group form-row col-12">
  	      <%=f.label :cc_type,
  	        class: "col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm 
                    label-bold" %>

          <%if action == "edit"%>
          <div class = "col-sm-4 col-md-3 col-lg-3">
            <%=f.hidden_field :cc_type, value: f.object.cc_type%>
            <%=content_tag(:i, '', class: credit_card.card_icon+" fa-2x")%>
          </div>
          <%else%>
  	      <div class = "col-sm-4 col-md-3 col-lg-3 col-xl-3">
  		      <%=f.select(:cc_type, [["Visa","V"],["MasterCard","M"], ["American Express","A"],["Discover","I"]],{include_blank: false},
  		        {class: 'form-control form-control-sm col',
               })%>
          </div>
          <%end%>
        </div>
      </div>
     
      <div class = "form-row col-12">
  	    <!-- NAME ON CARD -->
  	    <div class = "form-group form-row col-12">
  	      <%=f.label :cc_name,
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-5 col-md-5 col-lg-5 col-xl-4">
      	    <%= f.text_field :cc_name,
      	      class: "form-control form-control-sm col",
              required: true%>
          </div>   
  	    </div>
      </div>

      <div class = "form-row col-12">
  	    <!-- CARD NUMBER -->
  	    <div class = "form-group form-row col-12">
  	      <%=f.label :cc_number, 
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-4 col-md-4 col-lg-4 col-xl-4">
      	    <%= f.text_field :cc_number,
              class: "form-control form-control-sm col",
                required: true, maxlength: 16%>
          </div>   
  	    </div>
      </div>

      <div class = "form-row col-12">
        <!-- EXPIRATION -->
        <div class = "form-group form-row col-12">
          <%=f.label :cc_exp_month, 
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-2 col-md-2 col-lg-1 col-xl-1">
            <%=f.select(:cc_exp_month, '01'..'12', {},
          html_options ={:class => "form-control form-control-sm text-left col" })%> 
          
          </div>   

          <div class = "col-sm-1 col-md-1 col-lg-1 text-center">
            /
           </div>

          <div class = "col-sm-2 col-md-2 col-lg-1 col-xl-1">
            <%=f.select(:cc_exp_year, @years, {},
          html_options ={:class => "form-control form-control-sm text-left col" })%> 
          
          </div>   
        </div>
      </div>

      <div class = "form-row col-12">
        <!-- ADDRESS -->
        <div class = "form-group form-row col-12">
          <%=f.label :cc_address, 
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-6 col-md-6 col-lg-5">
            <%= f.text_field :cc_address,
              class: "form-control form-control-sm col",
                required: true, maxlength: 16%>
          </div>   
        </div>
      </div>

      <div class = "form-row col-12">
        <!-- CITY -->
        <div class = "form-group form-row col-12">
          <%=f.label :cc_city, 
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-6 col-md-6 col-lg-5">
            <%= f.text_field :cc_city,
              class: "form-control form-control-sm col",
                required: true, maxlength: 16%>
          </div>   
        </div>
      </div>

      <div class = "form-row col-12">
        <!-- STATE -->
        <div class = "form-group form-row col-12">
          <%=f.label :cc_state, 
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-2 col-md-2 col-lg-1 col-xl-1">
            <%= f.text_field :cc_state,
              class: "form-control form-control-sm col",
                required: true, maxlength: 16%>
          </div>   
        </div>
      </div>

      <div class = "form-row col-12">
        <!-- ZIP -->
        <div class = "form-group form-row col-12">
          <%=f.label :cc_zip, 
            class: 'col-md-3 col-sm-4 col-lg-3 col-xl-2
                    col-form-label-sm label-bold'%>
          <div class = "col-sm-3 col-md-3 col-lg-3 col-xl-2">
            <%= f.text_field :cc_zip,
              class: "form-control form-control-sm col",
                required: true, maxlength: 16%>
          </div>   
        </div>
      </div>


    </div>

</div>  

<br>

<div class = "row col-12">
  <%=f.submit (I18n.t('bank_account.form.save')),
    class: 'btn btn-padgett col-4 col-sm-4 col-md-3 col-lg-3 col-xl-2',
    name: "submit" %>
  <div class = "col-1 col-sm-1 col-md-1 col-lg-1">
  </div>
  
  <%=link_to (I18n.t('bank_account.form.discard')),
    bank_accounts_path,
    class: 'btn btn-padgett col-4 col-sm-4 col-md-3 col-lg-3 col-xl-2
      ' %>
</div>

  <%end%>  

app/views/credit_cards/edit.html.erb
<div class = "row justify-content-center">
  <div class = "col-12 col-sm-12 col-md-12 col-lg-10 col-xl-8">

  	<%= render :partial => "shared/error_handling",
    :locals => {:the_object => @credit_card,
    	        :objectname => I18n.t('credit_card.object_name')} %>

  	<%=render partial: 'form',
  	locals: { credit_card: @credit_card,
  				    action: 'edit'} %>
  </div>
</div>   	        

app/views/credit_cards/index.html.erb
<div class = "row col-12 pb-3">
  <%=link_to new_credit_card_path,
     data: {turbolinks: false} do%>
     <button class = 'btn btn-padgett'>
       <%=I18n.t('credit_card.index.add_credit_card')%>
     </button>
  <%end%>
</div>

<div class = "row">
	<div id = "credit_cards" class = "col">
		<%=render partial: 'credit_card_list'%>
	</div>
</div>

app/views/credit_cards/new.html.erb
<div class = "row justify-content-center">
  <div class = "col-12 col-sm-12 col-md-12 col-lg-10 col-xl-8">

  	<%= render :partial => "shared/error_handling",
    :locals => {:the_object => @credit_card,
    	        :objectname => I18n.t('credit_card.object_name')} %>

  	<%=render partial: 'form',
  	locals: { credit_card: @credit_card,
  				    action: 'new'} %>
  </div>
</div>   	        