config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Devise Routes for Admin
  
  devise_for :admins, path: 'admins', controllers: 
  {sessions: "admins/sessions",
   registrations: "admins/registrations",
   masquerades: "admins/masquerades"}
  
  # Devise Routes for Users
  devise_for :users, path: 'users', controllers: 
  {sessions: "users/sessions",
   registrations: "users/registrations",
   masquerades: "admins/masquerades"}

  resources :charts, only:[] do 
    collection do 
      get 'all_royalties_by_month'
      get 'revenue_by_state'
      get 'collections_by_category'
      get 'collections_by_month'
    end
  end
  
  # Custom Routes for Errors
  get '/404', :to => "errors#not_found"
  get '/422', :to => "errors#unacceptable"
  get '/500', :to => "errors#server_error"
  get '/cookies', :to => "cookies#index"
  
  # Routes for Signing Up
  get '/signup' => 'signups#index'
  post '/signup' => 'signups#create'

  # Authenticated route to show specific Dashboard for users
  authenticated :user do 
  	root to: 'public#userpage', as: "authenticated_user" 
    post '/' => 'public#userpage'
  end
  
  # Authenticate users before accessing these routes
  authenticate :user do  
    resources :users
    resources :franchises, only: [:edit, :update]
    resources :accountants, only: [:show]
    resources :insurances, only: [:show]
    resources :bank_accounts
    resources :credit_cards
    resources :website_preferences, except: :destroy
    resources :financials
    resources :remittances
    post '/remittances/new' => 'remittances#new'
    resources :franchise_documents, except: [:show, :edit, :update]
    resources :invoices
    resources :deposit_trackings


    get '/bank_routings/bank_name' => 'bank_routings#bank_name'
  end
  
  # Authenticated route to show specific Dashboard for admins
  authenticated :admin do 
  	root to: 'public#adminpage', as: "authenticated_admin" 
    post '/' => 'public#adminpage'
  end
  
  # Authenticate admins before accessing these routes
  authenticate :admin do 
    mount Logster::Web, at: "/logs"
    mount Sidekiq::Web => '/sidekiq'
    # Namespace the Admin pages
    namespace :admins do 
      resources :users
      resources :admins
      resources :franchises
      resources :franchises_select
      resources :credits
      resources :franchise_documents
      get 'credits/audit/:id', to: "credits#audit", as: 'credit_audit'
      resources :charges
      get 'charges/audit/:id', to: "charges#audit", as: 'charge_audit'
      get 'franchises/audit/:id' ,to: "franchises#audit", as: 'franchise_audit'
      resources :accountants
      get 'accountants/audit/:id' ,to: "accountants#audit", as: 'accountant_audit'
      resources :insurances
      get 'insurances/audit/:id' ,to: "insurances#audit", as: 'insurance_audit'
      resources :website_preferences
      get 'website_preferences/audit/:id', to: "website_preferences#audit", as: 'website_preference_audit'
      resources :financials
      get 'financials/audit/:id', to: "financials#audit", as: 'financials_audit'
      resources :remittances
      get 'remittances/audit/:id', to: "remittances#audit", as: 'remittances_audit'
      resources :invoices
      get 'invoices/audit/:id', to: "invoices#audit", as: 'invoices_audit'
      resources :transaction_codes
      get '/switch_user', to: "switch_user#index"

      #Reports
      scope module: :reports do 
        #Franchise List
        get '/franchise_list' => 'franchise_list#index'
        post '/franchise_list/render' => 'franchise_list#report'
        get '/franchise_list/render' => redirect('/admins/franchise_list')

        get '/franchise_expiration' => 'franchise_expiration#index'
        post '/franchise_expiration/render' => 'franchise_expiration#report'
        get '/franchise_expiration/render' => redirect('/admins/franchise_expiration')

        get '/franchise_advanced_rebate' => 'franchise_advanced_rebate#report'
        post '/franchise_advanced_rebate' => 'franchise_advanced_rebate#report'

        get '/franchise_prior_rebate' => 'franchise_prior_rebate#report'
        post '/franchise_prior_rebate' => 'franchise_prior_rebate#report'

        get '/insurance_expiration' => 'insurance_expiration#index'
        post '/insurance_expiration/render' => 'insurance_expiration#report'
        get '/insurance_expiration/render' => redirect('/admins/insurance_expiration')

        get '/insurance_missing' => 'insurance_missing#index'
        post '/insurance_missing/render' => 'insurance_missing#report'
        get '/insurance_missing/render' => redirect('/admins/insurance_missing')

        get '/payment_methods' => 'payment_methods#index'
        post '/payment_methods/render' => 'payment_methods#report'
        get '/payment_methods/render' => redirect('/admins/payment_methods')

        get 'payment_methods_missing' => 'payment_methods_missing#index'
        post '/payment_methods_missing/render' => 'payment_methods_missing#report'
        get '/payment_methods_missing/render' => redirect('/admins/payment_methods_missing')

        get '/website_preferences_list' => 'website_preferences_list#index'
        post '/website_preferences_list/render' => 'website_preferences_list#report'
        get '/website_preferences_list/render' => redirect('/admins/website_preferences_list')

        get '/website_preferences_missing' => 'website_preferences_missing#index'
        post '/website_preferences_missing/render' => 'website_preferences_missing#report'
        get '/website_preferences_missing/render' => redirect('/admins/website_preferences_missing')

        get '/financial_status' => 'financial_status#index'
        post '/financial_status/render' => 'financial_status#report'
        get '/financial_status/render' => redirect('/admins/financial_status')

        get '/financial_count_averages' => 'financial_count_and_averages#index'
        post '/financial_count_averages/render' => 'financial_count_and_averages#report'
        get '/financial_count_averages/render' => redirect('/admins/financial_count_averages')

        get '/financial_aggregation' => 'financial_aggregation#index'
        post '/financial_aggregation/render' => 'financial_aggregation#report'
        get '/financial_aggregation/render' => redirect('/admins/financial_aggregation')


      end

    end
  end
  
root to: 'public#main'
  
  
end

app/models/financial.rb
# frozen_string_literal: true

class Financial < ApplicationRecord
  extend FriendlyId
  belongs_to :franchise
  audited except: [:slug], on: %i[update destroy]
  friendly_id :number_name_year, use: :slugged
  attr_accessor :fran_number, :franchise_name,
                :average_monthly_fee, :average_quarterly_fee

  scope :all_ordered, -> { Financial.includes(:franchise).order('year DESC, id DESC') }
  scope :for_franchise, ->(fran_id) { where(franchise_id: fran_id).order('year DESC') }

  REVENUE_ATTRIBUTES = %w[acct_monthly acct_startup acct_backwork tax_prep payroll_processing other_consult].freeze
  REVENUE_DESC = %w[Accounting\ Monthly Startup Backwork Tax\ Preparation Payroll\ Processing Consulting].freeze
  EXPENSE_ATTRIBUTES = %w[payroll_operation owner_wages owner_payroll_taxes payroll_taxes_ben_ee insurance_business
                          supplies legal_accounting marketing rent outside_labor vehicles travel utilities licenses_taxes postage repairs interests meals_entertainment bank_charges contributions office miscellaneous equipment_lease dues_subscriptions bad_debt continuing_ed property_tax telephone_data_internet software royalties marketing_material owner_health_ins owner_vehicle owner_ira_contrib amortization depreciation payroll_process_fees].freeze
  EXPENSE_DESC = %w[Payroll\ -\ Operations Owner\ -\ Salary Owner\ -\ Payroll\ taxes Payroll\ taxes\ &\ Benefits\ EE
                    Insurance\ -\ Business Supplies Legal\ &\ Accounting Marketing\ Fees Rents Outside\ Labor Vehicles Travel Utilities Licenses\ &\ Taxes Postage Repairs\ &\ Maintenance Interests Meals\ &\ Entertainment Bank\ Charges Contributions Office Miscellaneous Equipment\ Leases Dues\ &\ Subscriptions Bad\ Debts Continuing\ Education Property\ Tax Telephone/Data/Internet Software Royalties Marketing\ Material Owner\ -\ Health\ Insurance Owner\ -\ Vehicle\ Use Owner\ -\ Retirement\ Contribution Amortization Depreciation Payroll\ Processing\ Fees].freeze
  OTHER_REVENUES = %w[other_income interest_income net_gain_asset casualty_gain].freeze
  OTHER_REVENUE_DESC = %w[Other\ Income Interest\ Income Net\ Gain/Loss\ Sale\ of\ Asset Casualty\ Gain/Loss].freeze
  OTHER_EXPENSES = %w[other_expense prov_income_tax other1 other2 other3].freeze
  OTHER_EXPENSE_DESC = %w[Other\ Expense Prov.\ for\ Income\ Tax Other1 Other2 Other3].freeze

  CLIENT_COUNTS = %w[monthly_clients total_monthly_fees quarterly_clients total_quarterly_fees].freeze

  EXPENSE_ATTRIBUTES_REPORT = %w[payroll_operation owner_wages owner_payroll_taxes payroll_taxes_ben_ee
                                 total_payroll_expense insurance_business supplies legal_accounting marketing rent outside_labor vehicles travel utilities licenses_taxes postage repairs interests meals_entertainment bank_charges contributions office miscellaneous equipment_lease dues_subscriptions bad_debt property_tax telephone_data_internet royalties marketing_material accounting_costs owner_health_ins owner_vehicle owner_ira_contrib depreciation_and_amortization payroll_process_fees].freeze
  EXPENSE_DESC_REPORT = %w[Payroll\ -\ Operations Owner\ -\ Salary Owner\ -\ Payroll\ taxes
                           Payroll\ taxes\ &\ Benefits\ EE Total\ Payroll\ Expense Insurance\ -\ Business Supplies Legal\ &\ Accounting Marketing\ Fees Rents Contractor Vehicles Travel Utilities Licenses\ &\ Taxes Postage Repairs\ &\ Maintenance Interests Meals\ &\ Entertainment Bank\ Charges Contributions Office Miscellaneous Equipment\ Leases Dues\ &\ Subscriptions Bad\ Debts Property\ Tax Telephone/Data/Internet Royalties Marketing\ Material Accounting\ Costs Owner\ -\ Health\ Insurance Owner\ -\ Vehicle\ Use Owner\ -\ Retirement\ Contribution Depreciation\ &\ Amortization Payroll\ Processing\ Fees].freeze
  OTHER_REVENUES_REPORT = %w[non_padgett_revenues net_gain_asset casualty_gain].freeze
  OTHER_REVENUE_DESC_REPORT = %w[Non\ Padgett\ Revenue Net\ Gain/Loss\ Sale\ of\ Asset Casualty\ Gain/Loss].freeze
  OTHER_EXPENSES_REPORT = %w[prov_income_tax other1 other2 other3].freeze
  OTHER_EXPENSE_DESC_REPORT = %w[Prov.\ for\ Income\ Tax Other1 Other2 Other3].freeze

  validates :year, presence: true
  validates :year, uniqueness: { scope: [:franchise_id], message: :year_unique }
  validates :other1_desc, presence: { if: :other1_entered? }
  validates :other2_desc, presence: { if: :other2_entered? }
  validates :other3_desc, presence: { if: :other3_entered? }
  validates_numericality_of REVENUE_ATTRIBUTES, { greater_than_or_equal_to: 0, message: :no_negative }
  validates_numericality_of EXPENSE_ATTRIBUTES, { greater_than_or_equal_to: 0, message: :no_negative }
  validates_numericality_of OTHER_EXPENSES, { greater_than_or_equal_to: 0, message: :no_negative }
  validates_numericality_of :other_income, { greater_than_or_equal_to: 0, message: :no_negative }
  validates_numericality_of :interest_income, { greater_than_or_equal_to: 0, message: :no_negative }
  validates_numericality_of CLIENT_COUNTS, { greater_than_or_equal_to: 0, message: :no_negative }

  before_validation :zero_if_nil

  def number_name_year
    [franchise&.number_and_name, year].join('-')
  end

  def other1_entered?
    other1.to_f > 0.00
  end

  def other2_entered?
    other2.to_f > 0.00
  end

  def other3_entered?
    other3.to_f > 0.00
  end

  def total_revenues
    REVENUE_ATTRIBUTES.reduce(0) { |sum, attribute| sum + self[attribute] }
  end

  def total_expenses
    EXPENSE_ATTRIBUTES.reduce(0) { |sum, attribute| sum + self[attribute] }
  end

  def self.get_history(franchise_id)
    Financial.select('year').where(franchise_id: franchise_id).order('year DESC')
  end

  def self.get_min_year
    Financial.minimum(:year)
  end

  def self.get_max_year
    Financial.maximum(:year)
  end

  private

  def zero_if_nil
    REVENUE_ATTRIBUTES.each { |attr| self[attr] = 0.00 if self[attr].nil? || self[attr].blank? }
    EXPENSE_ATTRIBUTES.each { |attr| self[attr] = 0.00 if self[attr].nil? || self[attr].blank? }
    OTHER_REVENUES.each { |attr| self[attr] = 0.00 if self[attr].nil? || self[attr].blank? }
    OTHER_EXPENSES.each { |attr| self[attr] = 0.00 if self[attr].nil? || self[attr].blank? }
    CLIENT_COUNTS.each { |attr| self[attr] = 0.00 if self[attr].nil? || self[attr].blank? }
  end
end

app/controllers/admins/financials_controller.rb
# frozen_string_literal: true

# For Admins to List, Add, Edit, Delete Financial Reports
class Admins::FinancialsController < ApplicationController
  before_action :set_financial, only: %i[audit edit update destroy]
  before_action :set_franchise, only: %i[create]

  def index
    @financials = Financial.all_ordered
    authorize! :read, Financial
  end

  def new
    redirect_to root_url, notice: I18n.t('franchise_not_selected') unless params[:franchise_id]
    franchise_id = params[:franchise_id].to_i
    @financial = Financial.new(franchise_id: franchise_id)
    authorize! :new, @financial
  end

  def create
    authorize! :create, Financial
    prepare_gon(@franchise.id)
    result = CreateFinancial.call(params: financial_params, user: current_authenticated)

    if result.success?
      flash[:success] = I18n.t('financial.create.confirm')
      redirect_to admins_financials_path
    else
      @financial = result.financial
      render action: :new
    end
  end

  def edit
    authorize! :edit, @financial
    prepare_gon(@financial.franchise_id)
  end

  def update
    prepare_gon(@financial.franchise_id)
    authorize! :update, @financial
    result = UpdateFinancial.call(financial: @financial,
                                  params: financial_params,
                                  user: current_authenticated)

    if result.success?
      flash[:success] = I18n.t('financial.update.confirm')
      redirect_to admins_financials_path
    else
      @financial = result.financial
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @financial
    if @financial.destroy
      flash[:success] = I18n.t('financial.delete.confirm')
    else
      flash[:danger] = @financial.errors.full_messages.to_sentence
    end
    redirect_to admins_financials_path
  end

  def show; end

  def audit
    @audits = @financial.audits.descending
  end

  private

  def set_financial
    @financial = Financial.friendly.find(params[:id])
  end

  def set_franchise
    @franchise = Franchise.find(financial_params[:franchise_id].to_i)
  end

  def financial_params
    params.require(:financial).permit(Financial.column_names - %w[created_at updated_at])
  end

  def prepare_gon(franchise_id)
    gon.previous = Financial.get_history(franchise_id)
  end
end

app/controllers/financials_controller.rb
# frozen_string_literal: true

# For User to List, Add, Edit, Delete Financial Reports
class FinancialsController < ApplicationController
  before_action :set_financial, only: %i[edit update show destroy]
  before_action :set_gon, only: %i[new create edit update]

  def index
    @financials = Financial.for_franchise(current_user.franchise_id)
    authorize! :read, Financial
  end

  def new
    @financial = current_user.franchise.financials.new
    authorize! :new, @financial
  end

  def create
    authorize! :create, Financial
    result = CreateFinancial.call(params: financial_params, user: current_authenticated)
    if result.success?
      flash[:success] = I18n.t('financial.create.confirm')
      redirect_to financials_path
    else
      @financial = result.financial
      render action: :new
    end
  end

  def edit
    authorize! :edit, @financial
    gon.previous = Financial.get_history(@financial.franchise_id)
  end

  def update
    authorize! :update, @financial
    result = UpdateFinancial.call(financial: @financial, params: financial_params, user: current_authenticated)
    if result.success?
      flash[:success] = I18n.t('financial.update.confirm')
      redirect_to financials_path
    else
      @financial = result.financial
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @financial
    if @financial.destroy
      flash[:success] = I18n.t('financial.delete.confirm')
    else
      flash[:danger] = @financial.errors.full_messages.to_sentence
    end
    redirect_to financials_path
  end

  private

  def financial_params
    params.require(:financial).permit(Financial.column_names - %w[created_at updated_at])
  end

  def set_financial
    @financial = Financial.friendly.find(params[:id])
  end

  def set_gon
    gon.previous = Financial.get_history(current_user.franchise_id)
  end
end

app/views/admins/financials/_counts.html.erb
<div class = "card">
	<div class = "card-header login-header">
		<h4>
			Client Counts & Total Fees <%=bubble_help(I18n.t('helpers.label.financial.client_counts_desc'),"right")%>
		</h4>
	</div>

<%label_classes = "col-md-8 col-sm-9 col-lg-7 col-xl-7 col-form-label-sm label-bold"%>
<%field_classes = "form-control form-control-sm text-right col-xl-4 col-lg-4 col-md-4 col-sm-3"%>

	<div class = "card-body card-background-padgett">
		<div class = "row">
			<div class = "container-fluid col-sm-6 no-gutters">
				<div class = "form-row col-12">
					<div class = "form-group form-row col-sm-12">
						<%=f.label :monthly_clients ,
						class: "#{label_classes}" do %>
	  			      <%= I18n.t('helpers.label.financial.monthly_clients')%> 
	  			      <%=bubble_help(I18n.t('helpers.label.financial.monthly_clients_desc'),"right")%>
	  			  <%end%>

	  			  <%=f.number_field :monthly_clients, 
	  			    step: "any", 
	  			    class: "#{field_classes}"%>
				  </div>

				  <div class = "form-group form-row col-sm-12">
						<%=f.label :quarterly_clients ,
						class: "#{label_classes}" do %>
	  			      <%= I18n.t('helpers.label.financial.quarterly_clients')%> 
	  			      <%=bubble_help(I18n.t('helpers.label.financial.quarterly_clients_desc'),"right")%>
	  			  <%end%>

	  			  <%=f.number_field :quarterly_clients, 
	  			    step: "any", 
	  			    class: "#{field_classes}"%>
				  </div>
				</div>
			</div>

			<div class = "container-fluid col-sm-6 no-gutters">
				<div class = "form-row col-12">
					<div class = "form-group form-row col-sm-12">
						<%=f.label :total_monthly_fees ,
						class: "#{label_classes}" do %>
	  			      <%= I18n.t('helpers.label.financial.total_monthly_fees')%> 
	  			      <%=bubble_help(I18n.t('helpers.label.financial.total_monthly_fees_desc'),"right")%>
	  			  <%end%>

	  			  <%=f.number_field :total_monthly_fees, 
	  			    step: "any", 
	  			    class: "#{field_classes}",
	  			    	value: (number_with_precision(f.object.total_monthly_fees, precision: 2))%>
				  </div>

				  <div class = "form-group form-row col-sm-12">
						<%=f.label :total_quarterly_feess ,
						class: "#{label_classes}" do %>
	  			      <%= I18n.t('helpers.label.financial.total_quarterly_fees')%> 
	  			      <%=bubble_help(I18n.t('helpers.label.financial.total_quarterly_fees_desc'),"right")%>
	  			  <%end%>

	  			  <%=f.number_field :total_quarterly_fees, 
	  			    step: "any", 
	  			    class: "#{field_classes}",
	  			    	value: (number_with_precision(f.object.total_quarterly_fees, precision: 2))%>
				  </div>
				</div>
			</div>
  	</div>
  </div>
</div>

app/views/admins/financials/_custom.html.erb
<div class = "card">
	<div class = "card-header login-header">
		<h4>
			Custom Accounts <%=bubble_help(I18n.t('helpers.label.financial.custom_accounts_desc'),"right")%>
		</h4>
	</div>

	<%label_classes = "col-md-3 col-sm-4 col-lg-2 col-xl-2 col-form-label-sm label-bold"%>
  <%number_classes = "form-control form-control-sm text-right col-xl-2 col-lg-3 col-md-3 col-sm-3"%>
  <%text_classes = "form-control form-control-sm text-left col-xl-7 col-lg-11 col-md-10 col-sm-10"%>

  
	<div class = "card-body card-background-padgett">
		<div class = "row">
			<div class = "form-row col-12">
				<div class = "form-group form-row col-sm-12">
					<%=f.label :other1_desc ,
						class: "#{label_classes}"%>

	  		  <%=f.text_field :other1_desc, 
	  		    class: "#{text_classes}"%>

	  		  <div class = "col-xl-1">
	  		  </div>

	  		  <%=f.number_field :other1, 
	  		  setp: "any",
	  		  class: "#{number_classes}"%>
			  </div>

			  <div class = "form-group form-row col-sm-12">
					<%=f.label :other2_desc ,
						class: "#{label_classes}"%>

	  		  <%=f.text_field :other2_desc, 
	  		    class: "#{text_classes}"%>

	  		  <div class = "col-xl-1">
	  		  </div>  

	  		  <%=f.number_field :other2, 
	  		  setp: "any",
	  		  class: "#{number_classes}"%>
			  </div>

			  <div class = "form-group form-row col-sm-12">
					<%=f.label :other3_desc ,
						class: "#{label_classes}"%>

	  		  <%=f.text_field :other3_desc, 
	  		    class: "#{text_classes}"%>

	  		  <div class = "col-xl-1">
	  		  </div>  

	  		  <%=f.number_field :other3, 
	  		  setp: "any",
	  		  class: "#{number_classes}"%>
			  </div>
			</div>
  	</div>
  </div>
</div>

app/views/admins/financials/_financial_list.html.erb
<div id = "table-scroll"
	 class = "table-scroll">
  <table id = "financial-list"
         class = "table-striped">
	<thead id = "list">
      <tr>
        <!-- Franchise -->
        <th scope = "col" class = "td-left">
            <%=I18n.t('financial.index.franchise')%>
        </th>
        <!-- Year -->
        <th scope = "col" class = "td-left">
        	<%=I18n.t('financial.index.year')%>
        </th>

        <!-- Received -->
        <th scope = "col" class = "td-left">
        	<%=I18n.t('financial.index.received')%>
        </th>

        <!-- Revenues -->
        <th scope = "col" class = "td-right">
            <%=I18n.t('financial.index.revenues')%>
        </th>        

        <!-- Expenses -->
        <th scope = "col" class = "td-right">
            <%=I18n.t('financial.index.expenses')%>
        </th>        

        <!-- Monthly Clients -->
        <th scope = "col" class = "td-center">
            <%=I18n.t('financial.index.monthly_clients')%>
        </th>        

        <!-- Total Monthly Fees -->
        <th scope = "col" class = "td-right">
            <%=I18n.t('financial.index.total_monthly_fees')%>
        </th>        

        <!-- Quarterly Clients -->
        <th scope = "col" class = "td-center">
            <%=I18n.t('financial.index.quarterly_clients')%>
        </th>        

        <!-- Total Quarterly Fees -->
        <th scope = "col" class = "td-right">
            <%=I18n.t('financial.index.total_quarterly_fees')%>
        </th>        
            
        <th></th>

        <th></th>

        <th></th>

      </tr>
    </thead>

    <% if @financials.size > 0 %>
      <tbody>    
    	<%@financials.each do |financial|%>
    	  <tr>
            <!-- Franchise  -->
            <td  data-name = "Franchise"
                 scope="col" 
                 class = "td-left">
              <%=financial.franchise.number_and_name %> 
            </td>
            <!-- Year -->
    	    <td data-name = "Year"
    	      	scope = "col"
    	      	class = "td-left">
    	  	    <%=financial.year%>
    	  	</td>

            <!-- Received-->
    	  	<td data-name = "Received" 
    	  	   	scope = "col"
    	  	   	class = "td-left">
     	  	    <%=I18n.l(financial.updated_at.in_time_zone, format: :prp)%>
    	  	</td>
            
            <!-- Revenues -->
            <td data-name = "Revenues" 
                scope = "col"
                class = "td-right">
                <%=number_to_currency(financial.total_revenues)%>
            </td>

            <!-- Expenses -->
            <td data-name = "Expenses" 
                scope = "col"
                class = "td-right">
                <%=number_to_currency(financial.total_expenses)%>
            </td>

            <!-- Monthly Clients -->
            <td data-name = "Monthly Clients" 
                scope = "col"
                class = "td-center">
                <%=financial.monthly_clients%>
            </td>

            <!-- Monthly Fees -->
            <td data-name = "Monthly Fees" 
                scope = "col"
                class = "td-right">
                <%=number_to_currency(financial.total_monthly_fees)%>
            </td>

            <!-- Quarterly Clients -->
            <td data-name = "Quarterly Clients" 
                scope = "col"
                class = "td-center">
                <%=financial.quarterly_clients%>
            </td>

            <!-- Quarterly Fees -->
            <td data-name = "Quarterly Fees" 
                scope = "col"
                class = "td-right">
                <%=number_to_currency(financial.total_quarterly_fees)%>
            </td>            
    	  	
            <!-- Edit Link if User can Edit -->
    	  	<%if can? :edit, financial %>
    	  	  <td data-name = ""
    	  	      class = "td-center">
    	  	      <%=link_with_icon(edit_admins_financial_path(financial),
    	  	      "edit",
    	  	      I18n.t('financial.index.edit_link'),
    	  	      "",
    	  	      false)%>
    	  	  </td>
    	  	<%else%>   
    	  	  <td></td>
    	  	<%end%>
            
            <!-- Delete Link if User can Delete -->
    	  	<%if can? :delete, financial%>
    	  	  <td data-name = ""
    	  	   	  class = "td-center">
    	  	      <%=link_with_icon(admins_financial_path(id: financial),
    	  	      "delete",
    	  	      I18n.t('financial.index.delete_link'),
    	  	      I18n.t('financial.index.delete_confirm'),false)%>
    	  	  </td>
    	  	<%else%>
    	  	  <td></td>
    	  	<%end%>

             <!-- Audit Icon and Link  -->
            <td data-name="" class = "td-center">
              <%if financial.audits.size > 0%>
                <%=link_with_icon(
                admins_financials_audit_path(id:financial),
                "audit",
                I18n.t('financial.index.audit_link'),
                "",
                false)%>
              <%end%>    
            </td>
    	  </tr>
   	  	<%end%>
      </tbody>
  	<%end%>
  </table>
</div>  	

app/views/admins/financials/audit.html.erb
<%=render partial: "shared/audit",
locals: {resource_name: @financial.franchise.full_denomination,
         audit_data: @audits} %>

app/views/admins/financials/index.html.erb
<div class = "row col-12 pb-3">
  <%=link_to admins_franchises_select_index_path(destination: 'add_financial'),
     data: {turbolinks: false} do%>
     <button class = 'btn btn-padgett'>
       <%=I18n.t('financial.index.add_financial')%>
     </button>
  <%end%>
</div>

<div class = "row">
	<div id = "financials" class = "col">
		<%=render partial: 'financial_list'%>
	</div>
</div>