config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Devise Routes for Admin
  
  devise_for :admins, path: 'admins', controllers: 
  {sessions: "admins/sessions",
   registrations: "admins/registrations",
   masquerades: "admins/masquerades"}
  
  # Devise Routes for Users
  devise_for :users, path: 'users', controllers: 
  {sessions: "users/sessions",
   registrations: "users/registrations",
   masquerades: "admins/masquerades"}

  resources :charts, only:[] do 
    collection do 
      get 'all_royalties_by_month'
      get 'revenue_by_state'
      get 'collections_by_category'
      get 'collections_by_month'
    end
  end
  
  # Custom Routes for Errors
  get '/404', :to => "errors#not_found"
  get '/422', :to => "errors#unacceptable"
  get '/500', :to => "errors#server_error"
  get '/cookies', :to => "cookies#index"
  
  # Routes for Signing Up
  get '/signup' => 'signups#index'
  post '/signup' => 'signups#create'

  # Authenticated route to show specific Dashboard for users
  authenticated :user do 
  	root to: 'public#userpage', as: "authenticated_user" 
    post '/' => 'public#userpage'
  end
  
  # Authenticate users before accessing these routes
  authenticate :user do  
    resources :users
    resources :franchises, only: [:edit, :update]
    resources :accountants, only: [:show]
    resources :insurances, only: [:show]
    resources :bank_accounts
    resources :credit_cards
    resources :website_preferences, except: :destroy
    resources :financials
    resources :remittances
    post '/remittances/new' => 'remittances#new'
    resources :franchise_documents, except: [:show, :edit, :update]
    resources :invoices
    resources :deposit_trackings


    get '/bank_routings/bank_name' => 'bank_routings#bank_name'
  end
  
  # Authenticated route to show specific Dashboard for admins
  authenticated :admin do 
  	root to: 'public#adminpage', as: "authenticated_admin" 
    post '/' => 'public#adminpage'
  end
  
  # Authenticate admins before accessing these routes
  authenticate :admin do 
    mount Logster::Web, at: "/logs"
    mount Sidekiq::Web => '/sidekiq'
    # Namespace the Admin pages
    namespace :admins do 
      resources :users
      resources :admins
      resources :franchises
      resources :franchises_select
      resources :credits
      resources :franchise_documents
      get 'credits/audit/:id', to: "credits#audit", as: 'credit_audit'
      resources :charges
      get 'charges/audit/:id', to: "charges#audit", as: 'charge_audit'
      get 'franchises/audit/:id' ,to: "franchises#audit", as: 'franchise_audit'
      resources :accountants
      get 'accountants/audit/:id' ,to: "accountants#audit", as: 'accountant_audit'
      resources :insurances
      get 'insurances/audit/:id' ,to: "insurances#audit", as: 'insurance_audit'
      resources :website_preferences
      get 'website_preferences/audit/:id', to: "website_preferences#audit", as: 'website_preference_audit'
      resources :financials
      get 'financials/audit/:id', to: "financials#audit", as: 'financials_audit'
      resources :remittances
      get 'remittances/audit/:id', to: "remittances#audit", as: 'remittances_audit'
      resources :invoices
      get 'invoices/audit/:id', to: "invoices#audit", as: 'invoices_audit'
      resources :transaction_codes
      get '/switch_user', to: "switch_user#index"

      #Reports
      scope module: :reports do 
        #Franchise List
        get '/franchise_list' => 'franchise_list#index'
        post '/franchise_list/render' => 'franchise_list#report'
        get '/franchise_list/render' => redirect('/admins/franchise_list')

        get '/franchise_expiration' => 'franchise_expiration#index'
        post '/franchise_expiration/render' => 'franchise_expiration#report'
        get '/franchise_expiration/render' => redirect('/admins/franchise_expiration')

        get '/franchise_advanced_rebate' => 'franchise_advanced_rebate#report'
        post '/franchise_advanced_rebate' => 'franchise_advanced_rebate#report'

        get '/franchise_prior_rebate' => 'franchise_prior_rebate#report'
        post '/franchise_prior_rebate' => 'franchise_prior_rebate#report'

        get '/insurance_expiration' => 'insurance_expiration#index'
        post '/insurance_expiration/render' => 'insurance_expiration#report'
        get '/insurance_expiration/render' => redirect('/admins/insurance_expiration')

        get '/insurance_missing' => 'insurance_missing#index'
        post '/insurance_missing/render' => 'insurance_missing#report'
        get '/insurance_missing/render' => redirect('/admins/insurance_missing')

        get '/payment_methods' => 'payment_methods#index'
        post '/payment_methods/render' => 'payment_methods#report'
        get '/payment_methods/render' => redirect('/admins/payment_methods')

        get 'payment_methods_missing' => 'payment_methods_missing#index'
        post '/payment_methods_missing/render' => 'payment_methods_missing#report'
        get '/payment_methods_missing/render' => redirect('/admins/payment_methods_missing')

        get '/website_preferences_list' => 'website_preferences_list#index'
        post '/website_preferences_list/render' => 'website_preferences_list#report'
        get '/website_preferences_list/render' => redirect('/admins/website_preferences_list')

        get '/website_preferences_missing' => 'website_preferences_missing#index'
        post '/website_preferences_missing/render' => 'website_preferences_missing#report'
        get '/website_preferences_missing/render' => redirect('/admins/website_preferences_missing')

        get '/financial_status' => 'financial_status#index'
        post '/financial_status/render' => 'financial_status#report'
        get '/financial_status/render' => redirect('/admins/financial_status')

        get '/financial_count_averages' => 'financial_count_and_averages#index'
        post '/financial_count_averages/render' => 'financial_count_and_averages#report'
        get '/financial_count_averages/render' => redirect('/admins/financial_count_averages')

        get '/financial_aggregation' => 'financial_aggregation#index'
        post '/financial_aggregation/render' => 'financial_aggregation#report'
        get '/financial_aggregation/render' => redirect('/admins/financial_aggregation')


      end

    end
  end
  
root to: 'public#main'
  
  
end

app/models/franchise_document.rb
# frozen_string_literal: true

class FranchiseDocument < ApplicationRecord
  belongs_to :franchise
  has_one_attached :document

  validates :description, presence: true
  validates :document_type, presence: true
  validates :document,
            attached: true,
            content_type: [:gif, :png, :jpg, :jpeg, :pdf, :xls, :xlsx, :tif, 'application/msword',
                           'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            size: { less_than: 10.megabytes, message: 'Document must be less than 10Mb' }

  enum document_type: { 'tax return' => 1, 'insurance' => 2, 'other' => 5 }

  scope :for_franchise, lambda { |fran_id|
                          FranchiseDocument.includes(document_attachment: :blob).where(franchise_id: fran_id).order('created_at DESC')
                        }
  scope :all_ordered, lambda {
                        FranchiseDocument.includes(:franchise, document_attachment: :blob).order('created_at DESC')
                      }
end

app/controllers/admins/franchise_documents_controller.rb
# frozen_string_literal: true

# For Admins to List, Add, Edit, Delete Franchise Documents
class Admins::FranchiseDocumentsController < ApplicationController
  before_action :set_franchise_document, only: %i[destroy]

  def index
    @franchise_documents = FranchiseDocument.all_ordered
                                            .paginate(per_page: 20, page: params[:page])
    authorize! :read, FranchiseDocument
  end

  def new
    redirect_to root_url, notice: I18n.t('franchise_not_selected') unless params[:franchise_id]

    franchise_id = params[:franchise_id].to_i
    @franchise_document = FranchiseDocument.new(franchise_id: franchise_id)
    authorize! :new, @franchise_document
  end

  def create
    authorize! :create, FranchiseDocument
    result = CreateFranchiseDocument.call(params: franchise_document_params)
    if result.success?
      flash[:success] = I18n.t('franchise_document.create.confirm')
      redirect_to admins_franchise_documents_path
    else
      @franchise_document = result.franchise_document
      render action: :new
    end
  end

  def destroy
    authorize! :destroy, @franchise_document
    if @franchise_document.destroy
      flash[:success] = I18n.t('franchise_document.delete.confirm')
    else
      flash[:danger] = @franchise_document.errors.full_messages.to_sentence
    end
    redirect_to admins_franchise_documents_path
  end

  private

  def set_franchise_document
    @franchise_document = FranchiseDocument.find(params[:id])
  end

  def franchise_document_params
    params.require(:franchise_document).permit(:franchise_id, :description, :document_type, :document)
  end
end

app/controllers/franchise_documents_controller.rb
# frozen_string_literal: true

# For User to List, Add, Edit, Delete Documents
class FranchiseDocumentsController < ApplicationController
  before_action :set_franchise_document, only: [:destroy]

  def index
    @franchise_documents = FranchiseDocument.for_franchise(current_user.franchise_id)
                                            .paginate(per_page: 20, page: params[:page])
    authorize! :read, FranchiseDocument
  end

  def new
    @franchise_document = current_user.franchise.franchise_documents.new
    authorize! :new, @franchise_document
  end

  def create
    authorize! :create, FranchiseDocument
    result = CreateFranchiseDocument.call(params: franchise_document_params)

    if result.success?
      flash[:success] = I18n.t('franchise_document.create.confirm')
      redirect_to franchise_documents_path
    else
      @franchise_document = result.franchise_document
      render action: :new
    end
  end

  def destroy
    if @franchise_document.destroy
      flash[:success] = I18n.t('franchise_document.delete.confirm')
    else
      flash[:danger] = @franchise_document.errors.full_messages.to_sentence
    end
    redirect_to franchise_documents_path
  end

  private

  def franchise_document_params
    params.require(:franchise_document).permit(:franchise_id, :description, :document_type, :document)
  end

  def set_franchise_document
    @franchise_document = FranchiseDocument.find(params[:id])
  end
end

app/views/franchise_documents/_document_list.html.erb
<div id = "table-scroll"
	   class = "table-scroll">
  <table id = "document-list"
         class = "table-striped">
	  <thead id = "list">
      <tr>
        <!-- Uploaded -->
        <th scope = "col" class = "td-left">
          <%=I18n.t('franchise_document.index.uploaded')%>
        </th>

        <!-- Document Type -->
        <th scope = "col" class = "td-left">
          <%=I18n.t('franchise_document.index.document_type')%>
        </th>

        <!-- Description -->
        <th scope = "col" class = "td-left">
          <%=I18n.t('franchise_document.index.description')%>
        </th>        

        <!-- Size -->
        <th scope = "col" class = "td-left">
          <%=I18n.t('franchise_document.index.size')%>
        </th>        

        <!-- Link -->
        <th scope = "col" class = "td-left">
          <%=I18n.t('franchise_document.index.document_file')%>
        </th>        

        <th></th>

      </tr>
    </thead>

    <% if @franchise_documents.size > 0 %>
      <tbody>    
    	<%@franchise_documents.each do 
          |franchise_document|%>
    	  <tr>
          <!-- Uploaded On -->
    	    <td data-name = "Uploaded On"
    	      	scope = "col"
    	      	class = "td-left">
    	  	    <%=I18n.l(franchise_document.created_at.in_time_zone, format: :prp)%>
    	  	</td>

          <!-- Document Type-->
    	  	<td data-name = "Type" 
    	  	   	scope = "col"
    	  	   	class = "td-left">
     	  	    <%=franchise_document.document_type.capitalize%>
    	  	</td>
            
          <!-- Description -->
          <td data-name = "Description" 
              scope = "col"
              class = "td-left">
              <%=franchise_document.description%>
          </td>

          <!-- Size -->            
          <td date-name = "Size"
              scope = "col"
              class = "td-left">
              <%=number_to_human_size(franchise_document.document.byte_size)%>
          </td>

          <!-- File -->
          <td data-name = "File" 
              scope = "col"
              class = "td-left">
              <%=link_to (franchise_document.document.filename), 
              rails_blob_url(franchise_document.document,disposition: 'attachment')%>
          </td>
            
            <!--Delete Link if User can Delete -->
    	  	<%if can? :delete, franchise_document%>
    	  	  <td data-name = ""
    	  	   	  class = "td-center">
    	  	      <%=link_with_icon(franchise_document_path(
                      id: franchise_document.id),
    	  	      "delete",
    	  	      I18n.t('franchise_document.index.delete_link'),
    	  	      I18n.t('franchise_document.index.delete_confirm'),
                  false)%>
    	  	  </td>
    	  	<%else%>
    	  	  <td></td>
    	  	<%end%>
    	  </tr>
   	  	<%end%>
      </tbody>
  	<%end%>
  </table>
</div> 

<!-- Pagination Links  -->
<div class = "row justify-content-center">
  <div class = "flickr_pagination">
    <%= will_paginate @franchise_documents,
    pervious_label: I18n.t('pagination.prev'),
    next_label: I18n.t('pagination.next') %>
  </div>
</div> 	

app/views/franchise_documents/_form.html.erb
<div class = "card">
  <div class = "card-header login-header">
    <h4>
      <%=I18n.t('franchise_document.form.create_title')%>
    </h4>
  </div>
  
  <%= form_for franchise_document, html: {multipart: true} do |f| %>
    <div class = "card-body card-background-padgett">
      <div class = "form-row col-12">
        <%=f.hidden_field :franchise_id,
           value: f.object.franchise_id%>
        <!-- TYPE -->
        <div class = "form-group form-row col-12">
          <%=f.label :document_type,
            class: 'col-md-3 col-sm-3 col-lg-2 col-xl-3
                    col-form-label col-form-label-sm
                    label-bold'%>
          <div class = "col-sm-3 col-md-2 col-lg-2 col-xl-2">
            <%= f.select(:document_type,
              [["Tax Return",1],
               ["Insurance",2],
               ["Other",5]],{include_blank: false},
               {class: "form-control form-control-sm col"})%>
          </div>   
        </div>
      </div>

      <div class = "form-row col-12">  
        <!-- DESCRIPTION -->   
        <div class = "form-group form-row col-12">
          <%=f.label :description,
           class: 'col-md-3 col-sm-3 col-lg-2 col-xl-3 
                   col-form-label col-form-label-sm
                   label-bold'%>
          <div class = "col-sm-6 col-md-6 col-lg-6 col-xl-6">
      	    <%= f.text_field :description,
      	    class: "form-control form-control-sm col",
              required: true%>
          </div>
        </div>
      </div>
     
      <div class = "form-row col-12">
  	    <!-- FILE TO UPLOAD -->
  	    <div class = "form-group form-row col-12">
          <%=f.label :document,
            class: 'col-md-3 col-sm-3 col-lg-2 col-xl-3
                    col-form-label col-form-label-sm
                    label-bold'%>
                    
          <div class = "col-sm-6 col-md-6 col-lg-6 col-xl-6">
            <label class="btn btn-padgett"
                   for="franchise_document_document">
            
              <input id="franchise_document_document" type="file" class = "hidden_field" name="franchise_document[document]"  
              onchange="$('#upload-file-info').text(this.files[0].name)">
              Select File
            </label>
            &nbsp;
            <span class='label label-info'
            id="upload-file-info">
              No File Selected
            </span>
          </div>            
  	      
  	    </div>
     </div>
    </div>
 </div>     
<br/>
<div class = "row col-12">
  <%=f.submit (I18n.t('franchise_document.form.save')),
    class: 'btn btn-padgett col-4 col-sm-4 col-md-3
      col-lg-3 col-xl-2', name: "submit" %>
  <div class = "col-1 col-sm-1 col-md-1
               col-lg-1 col-xl-1">
  </div>
  <%=link_to (I18n.t('franchise_document.form.discard')),
    franchise_documents_path,
    class: 'btn btn-padgett col-4 col-sm-4 col-md-3
    col-lg-3 col-xl-2' %>
</div>

<%end%>

app/views/franchise_documents/index.html.erb
<div class = "row col-12 pb-3">
  <%=link_to new_franchise_document_path,
     data: {turbolinks: false} do%>
     <button class = 'btn btn-padgett'>
       <%=I18n.t('franchise_document.index.add_document')%>
     </button>
  <%end%>
</div>

<div class = "row">
	<div id = "documents" class = "col">
		<%=render partial: 'document_list'%>
	</div>
</div>

app/views/franchise_documents/new.html.erb
<div class = "row justify-content-center">
  <div class = "col-12 col-sm-12 col-md-12 col-lg-10 col-xl-8">
		<%= render partial: "shared/error_handling",
 			locals:{the_object: @franchise_document,
       				objectname: I18n.t('franchise_document.object_name')} %>

    <%=render partial: 'form',
    	locals: {franchise_document: @franchise_document,
	             action: 'new'} %>
  </div>
</div>